name       : libqalculate
version    : 2.0.0
release    : 2
source     :
    - https://github.com/Qalculate/libqalculate/releases/download/v2.0.0/libqalculate-2.0.0.tar.gz : 86d04362f37aa5acbc78108e0044b96fbffbaa33c309c19c8c37ac4fb46c5485
license    : GPL-2.0
component  : programming
summary    : Qalculate! library and CLI
description: |
    Qalculate! library and CLI
builddeps  :
    - pkgconfig(icu-uc)
    - pkgconfig(libcurl)
rundeps    :
    - gnuplot
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
