name       : libqalculate
version    : 2.2.1
release    : 6
source     :
    - https://github.com/Qalculate/libqalculate/releases/download/v2.2.1/libqalculate-2.2.1.tar.gz : 1752b6a046eaf84ee62a7dc8d2c874b538517956ce8affac80df09a3b55bef5d
license    : GPL-2.0
component  : programming
summary    : Qalculate! library and CLI
description: |
    Qalculate! library and CLI
builddeps  :
    - pkgconfig(icu-uc)
    - pkgconfig(libcurl)
rundeps    :
    - gnuplot
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
