name       : libqalculate
version    : 3.22.0
release    : 21
source     :
    - https://github.com/Qalculate/libqalculate/releases/download/v3.22.0/libqalculate-3.22.0.tar.gz : 533ec2fc3550b44a562e4ff93f2bb21332c802c60d13ae1323bfa54ffe5d57f6
license    : GPL-2.0-or-later
component  : programming
summary    : Qalculate! library and CLI
description: |
    Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple to use but provides power and versatility normally reserved for complicated math packages, as well as useful tools for everyday needs (such as currency conversion and percent calculation). Features include a large library of customizable functions, unit calculations and conversion, symbolic calculations (including integrals and equations), arbitrary precision, interval arithmetic, plotting, and a user-friendly interface.
builddeps  :
    - pkgconfig(icu-uc)
    - pkgconfig(libcurl)
rundeps    :
    - gnuplot
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
