name       : libqalculate
version    : 2.1.0
release    : 3
source     :
    - https://github.com/Qalculate/libqalculate/releases/download/v2.1.0/libqalculate-2.1.0.tar.gz : 7668ed9ab32d46d3638297985a03bc995b6aedf8b8335685e1a43393ba236f12
license    : GPL-2.0
component  : programming
summary    : Qalculate! library and CLI
description: |
    Qalculate! library and CLI
builddeps  :
    - pkgconfig(icu-uc)
    - pkgconfig(libcurl)
rundeps    :
    - gnuplot
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
