name       : libqalculate
version    : 2.2.0
release    : 5
source     :
    - https://github.com/Qalculate/libqalculate/releases/download/v2.2.0/libqalculate-2.2.0.tar.gz : 1f02c58cc14e899a77970d3ad97afe4e3a765e6b602b3f3d38fbc5039d466288
license    : GPL-2.0
component  : programming
summary    : Qalculate! library and CLI
description: |
    Qalculate! library and CLI
builddeps  :
    - pkgconfig(icu-uc)
    - pkgconfig(libcurl)
rundeps    :
    - gnuplot
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
