name       : libqalculate
version    : 0.9.10
release    : 1
source     :
    - https://github.com/Qalculate/libqalculate/releases/download/v0.9.10/libqalculate-0.9.10.tar.gz : 7d81e1b15bc1e674e3d4db71c4fc08dafcef830e6acd39f65034e3c0f694b3b9
license    : GPL-2.0
component  : programming
summary    : Qalculate! library and CLI
description: |
    Qalculate! library and CLI
builddeps  :
    - pkgconfig(cln)
    - gnuplot
    - gvfs-devel
rundeps    :
    - gnuplot
    - gvfs
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
